language: node_js
node_js:
- node
script:
- npm i
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAINA3HRDOPMJGPGPQ
  secret_access_key:
    secure: 1B4jj+uyMcNT5KHQraJZLFIeTXM2rqwMtNRpSXMO6ojoPE8Q7Jtsc2bwtCLOJ6y/vSIgVwwcYAsMYZBoMESzJNwZ47WtwfHRU80GDNwsDUo1c379SZ5PuZPjZdheSYcbaqQk7mW1qVG02yz8Oa1q6PTAlKKEOF4ALf++PDuZGEOGNNPA1vVJyjL0p6IX/vnIesQSt33Rg5eWu6iAdKVJdqeBdS7nIY+BL7Nb4ZR4FDsjxpcF+R/LO2PoOnoFKIxebF87ghfgPTCPkVxCPESPhDzk3iDIZ0NIKIvEZy4C4KKlMEGooBBtu7WS4Ym7G/bLKs10n/CEcvJzuuh6DlXdvGgDzl+DCSBz0aKHz7QQrHgSXp126L+eQfB3XdtX4J5OLYcTpr7dN4eJy7W99RKnLJCFekDLhKC6x9U4EwetJyDxTGFyrZ71pLl++Rvq6b47j0QzKK+/WKpsaE7Gg6f0434WqVLzsn6v7tVROG7NBdX6xjmQYbCObVQzW6RtV8AZGRtrZ6G0dG9+7cpzIn8PZN37r++ikqwyYOnkKmaJncfe5rE0l32kSRteRf9MERNRL1nQTpWP2JA0fXIIMwxwdw3Z+f8s7T9qoFdDeQe/LasQDOc4kdNwQQldGGLdTAjfB9gDIv0SrOGvD52asINZBnLxgV6F6YHtyKA9YeHTuhw=
  bucket: flindt.wearespindle.com
  region: eu-west-1
  acl: public_read
  skip_cleanup: true
  local_dir: build
  on:
    repo: wearespindle/flindt-front-end
branches:
  only:
  - master
  - "/^hotfix/"
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: hTr3o0fY3iLktG21ZUgOU7sPKFIDRa0U8vvpFFIQI64zmyf60uCTWmzMozRkDNk8iWgedwmcL+CZKrcBpLWekHt0HivmD+xGVIjdtZDNfLN5gdGNAbS/UKzx2Axt5HTca84jAa8Ukgq601c0uNKfQlwHMAamL/rI9Z+H4YSLcbeQclNbcxqzaOgb6osKOAwSOete9j7JW0wa4s6Vb4ETVPAFR7vICYuH4jzG4C5BURgYZHp3CO9GlIaYcoI1lt6r/868Y5qt5v61h2v1jz2ZcV7sfxsEuDe0zpQjqhEaDzTaA6WLoQWWmZUDii3Rw6X8ByZtMUrhbk+HL9FLxpFTi45WZzE+kMZcg1cMNydMVxHv9knvAW4IIGrCJqBgH72lGEf9rJTqgUEUFvgzm8Bf4JoOHJCCN698YnHmphPzVg8DlPIDvs8Y55PeLgnk+ARWD+CzNotPWJcRomvz9FnmRMEW7v0a6s26JPNHzeUDcZvB36d66iwexb8cA/FvZzbHDQo34YO1hQmW0S3iLYvGJN95OvTVGoN3K0STgJwAr7gG3DzJ7LtGRebGGGZwekFreZk+g4e9GHGVZd2d+Ve335yfRuV/w4he/i848qFP0cHvFdb9sOBg62MZiA1nM5dN/z66yKqWx5ej4n/u/wdN08H5BIRLjb5E8n7UOMyUXxw=
