language: node_js
node_js:
- node
script:
- npm i
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAINA3HRDOPMJGPGPQ
  secret_access_key:
    secure: 1B4jj+uyMcNT5KHQraJZLFIeTXM2rqwMtNRpSXMO6ojoPE8Q7Jtsc2bwtCLOJ6y/vSIgVwwcYAsMYZBoMESzJNwZ47WtwfHRU80GDNwsDUo1c379SZ5PuZPjZdheSYcbaqQk7mW1qVG02yz8Oa1q6PTAlKKEOF4ALf++PDuZGEOGNNPA1vVJyjL0p6IX/vnIesQSt33Rg5eWu6iAdKVJdqeBdS7nIY+BL7Nb4ZR4FDsjxpcF+R/LO2PoOnoFKIxebF87ghfgPTCPkVxCPESPhDzk3iDIZ0NIKIvEZy4C4KKlMEGooBBtu7WS4Ym7G/bLKs10n/CEcvJzuuh6DlXdvGgDzl+DCSBz0aKHz7QQrHgSXp126L+eQfB3XdtX4J5OLYcTpr7dN4eJy7W99RKnLJCFekDLhKC6x9U4EwetJyDxTGFyrZ71pLl++Rvq6b47j0QzKK+/WKpsaE7Gg6f0434WqVLzsn6v7tVROG7NBdX6xjmQYbCObVQzW6RtV8AZGRtrZ6G0dG9+7cpzIn8PZN37r++ikqwyYOnkKmaJncfe5rE0l32kSRteRf9MERNRL1nQTpWP2JA0fXIIMwxwdw3Z+f8s7T9qoFdDeQe/LasQDOc4kdNwQQldGGLdTAjfB9gDIv0SrOGvD52asINZBnLxgV6F6YHtyKA9YeHTuhw=
  bucket: feedbag.wearespindle.com
  region: eu-west-1
  acl: public_read
  skip_cleanup: true
  local_dir: build
  on:
    repo: wearespindle/flindt-front-end
branches:
  only:
  - master
  - "/^hotfix/"
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: DGAY3LlgCUUfSJBQnyEomSAziQbm6L3QHwjYwLx5uNvH9QSy0tXUhy0I/NR/EIynRatKnXW95KpEM1Tur5LtvdFX/k+1H3udmahjLiqPIzl/UGATBHBtQQmDg0qaNkDqS6Vj3kI3EwiXi3/F+4cKIltIpKy/i9kTsClanFENfSo8VJhjh/78WlA+7hlqQ0gbNTzuFLXqlw3btmVgg8Uoi+fxkUFzxEDyelbG61bwZapA4WuzXfsROiuFjLoB0Yb+NJEen2ELqX0hhn69l21AbAvAcMIBkTmdAkEJhoALK08MNAgMJhJ7D/hWjE86BwsxhKhOCuu/IlMZbeUFf2RzJwjqu0lW3oZ/qliEhXn33WLiSB1LanOuz/Gxih/sgXJ4H7E/NuUPcDTZEfA3SN42LHST/nMwPRVpqKFcDosJlgd4K0IWzMeFIOc6IDGHY5e9/XFPs+pIkEpgzc+03uh9Sspni4xKxIBESKVuqs+eA8yPV2B7HqCO7+BYNVLeeLW2IwU/hEQ5aaE8qQ9YmgBHXi/DXPzRNk6rCjPqX/BAzOusBW8lqjCREm+X55H7cKDii/0LQpzUJs14gt9ALd6L9X990ODQ0QY8SmgQM7244whRu8qv4k3QvdTArt6ou/E5+aFLAK9VOLvZOSRJr37cf9yoEh2Rv+Gdpgn/HubgbHE=
