language: node_js
node_js:
- node
script:
- npm i
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAINA3HRDOPMJGPGPQ
  secret_access_key:
    secure: uEW0TaFx2kthh4YX9Put+7rBQRer+tJQYuEjtsaqXdOw1pezc7BBIaT5s80YgGrfd+X3xy46sa5MlAL4WQ+xRfxWH24kCszrjIXegVTDJIrzBsMp88lFesa+2kVsuVDsIjrgYgPVN6LjKneJ+NcvpmedUYxTNxmC7xhucjCH/d9nxAwhnkvopE+OjFQHNJANI7jylTYmU0iF8I+wJOw1Ut8IpBVetbnOxhhfLLRwKmq7aavCMfddw8t4arcVwWi+DB2O9+hXLq/+/qUHo3TiB00O0+eTBL8dkzYGAHZFiME6q0FMq57tRoQkMTXVn+rdonaFjrKjxrdbXhDXZjX7zdETT7PmgrxFOH5zce1/lKpq2QzNyvfObAd44NNagpsNFYEW2/rYbEYxgAzAq8IzEg5i3hyoxB7o8qZw6DBkDhV1sKc2EPKOSKeVicj2TGz/zB7GNK5e/KsyNckrvrFXGUgKfNZ1x9e0xxjF0hNF8xQgqAwhqTfKB55WbrwHhk5YHxC/HZILJ+Bc2NoDfwVfU68GA4dFrClQoq369Fv1j849QvY0iHdJ3YndNIV/SJEvsj6iJRBqxLQSvmO3mFQ3fQegbRKzJ5OvHHWbss0pSa1mVqc6YUaRyWuh+evuwZ4bS8Nb0tVHh8u9KME8lw2Nw0iDB355Y9PnzduMDX3yeMg=
  bucket: feedbag.wearespindle.com
  region: eu-west-1
  acl: public_read
  skip_cleanup: true
  local_dir: build
branches:
  only:
  - master
  - "/^hotfix/"
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: hTr3o0fY3iLktG21ZUgOU7sPKFIDRa0U8vvpFFIQI64zmyf60uCTWmzMozRkDNk8iWgedwmcL+CZKrcBpLWekHt0HivmD+xGVIjdtZDNfLN5gdGNAbS/UKzx2Axt5HTca84jAa8Ukgq601c0uNKfQlwHMAamL/rI9Z+H4YSLcbeQclNbcxqzaOgb6osKOAwSOete9j7JW0wa4s6Vb4ETVPAFR7vICYuH4jzG4C5BURgYZHp3CO9GlIaYcoI1lt6r/868Y5qt5v61h2v1jz2ZcV7sfxsEuDe0zpQjqhEaDzTaA6WLoQWWmZUDii3Rw6X8ByZtMUrhbk+HL9FLxpFTi45WZzE+kMZcg1cMNydMVxHv9knvAW4IIGrCJqBgH72lGEf9rJTqgUEUFvgzm8Bf4JoOHJCCN698YnHmphPzVg8DlPIDvs8Y55PeLgnk+ARWD+CzNotPWJcRomvz9FnmRMEW7v0a6s26JPNHzeUDcZvB36d66iwexb8cA/FvZzbHDQo34YO1hQmW0S3iLYvGJN95OvTVGoN3K0STgJwAr7gG3DzJ7LtGRebGGGZwekFreZk+g4e9GHGVZd2d+Ve335yfRuV/w4he/i848qFP0cHvFdb9sOBg62MZiA1nM5dN/z66yKqWx5ej4n/u/wdN08H5BIRLjb5E8n7UOMyUXxw=
