language: node_js
node_js:
- node
script:
- npm i
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAINA3HRDOPMJGPGPQ
  secret_access_key:
    secure: 1B4jj+uyMcNT5KHQraJZLFIeTXM2rqwMtNRpSXMO6ojoPE8Q7Jtsc2bwtCLOJ6y/vSIgVwwcYAsMYZBoMESzJNwZ47WtwfHRU80GDNwsDUo1c379SZ5PuZPjZdheSYcbaqQk7mW1qVG02yz8Oa1q6PTAlKKEOF4ALf++PDuZGEOGNNPA1vVJyjL0p6IX/vnIesQSt33Rg5eWu6iAdKVJdqeBdS7nIY+BL7Nb4ZR4FDsjxpcF+R/LO2PoOnoFKIxebF87ghfgPTCPkVxCPESPhDzk3iDIZ0NIKIvEZy4C4KKlMEGooBBtu7WS4Ym7G/bLKs10n/CEcvJzuuh6DlXdvGgDzl+DCSBz0aKHz7QQrHgSXp126L+eQfB3XdtX4J5OLYcTpr7dN4eJy7W99RKnLJCFekDLhKC6x9U4EwetJyDxTGFyrZ71pLl++Rvq6b47j0QzKK+/WKpsaE7Gg6f0434WqVLzsn6v7tVROG7NBdX6xjmQYbCObVQzW6RtV8AZGRtrZ6G0dG9+7cpzIn8PZN37r++ikqwyYOnkKmaJncfe5rE0l32kSRteRf9MERNRL1nQTpWP2JA0fXIIMwxwdw3Z+f8s7T9qoFdDeQe/LasQDOc4kdNwQQldGGLdTAjfB9gDIv0SrOGvD52asINZBnLxgV6F6YHtyKA9YeHTuhw=
  bucket: feedbag.wearespindle.com
  region: eu-west-1
  acl: public_read
  skip_cleanup: true
  local_dir: build
  on:
    repo: wearespindle/flindt-front-end
branches:
  only:
  - master
  - "/^hotfix/"
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: re6jnSR7H2XcGwTbnyykKN6hGkn+JqC3J1oVHXVSG+KFjxA3Tq4vof0CUIgTcLeThXjkQVKWWkEtUPvh7t1duAxyIMFYKs35KeBycpB6D7QiPxPXUmL3Hh+6TTkxWhN5DofN0gaMBG2eIfBAaz9PpK5CQHuOKoXRxN21i9U6ZEN9qohV1oBcCpcsXD6W9amItkRnC7Iric3tFhSe98Y+dM9SfzyVxAHBBddyDkSqawJDKS638Wkb1Oyt0l1E8DyHuktRrElpG9yP8c0greaUc6/+ZcmJc1hJIaZbS1Orvd2EhAX7RXWOTaoAQ1VB/KL3dCQ3S4emYOd71zVjA4EB8agToQSQkuFtjOGSvvnLhf4gc4LUW46kaKa3tJvh8dxrX1cNol4DUJ5wig1ZITJZa+hwClbTE5DgrqQn0kT6fH6uhxGEFUfOsIPA5XkgjLRFy4PUYkXiVXKboBLf6EBLQuWin/MB/421ORELSXQGaNVhBgVbDvqKeyVUNl8QhLg34lpRbvrEn9vS6WaeQFGZnXtRjazDrhJJ4zNrEnlUdZKclcRwybORgl28abbECDLGWgZTdtZw/tWTMjCO+k/pTGZDkXwHjlAkQbTcjNqQn52g2cFVeQqG+3OEAqra2Rp8QhxEmeGgta37fp/p3+/3xE8lq3spXd99YFrhFcx9vjQ=
